import { StyleSheet } from 'react-native';
import { theme } from './theme';

export const detailScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.white,
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: theme.spacing.xxl,
    },
    imageContainer: {
        width: '100%',
        height: 450,
        backgroundColor: theme.colors.secondary,
        ...theme.shadows.medium,
        position: 'relative',
    },
    image: {
        width: '100%',
        height: '100%',
        borderBottomLeftRadius: theme.borderRadius.xl,
        borderBottomRightRadius: theme.borderRadius.xl,
    },
    imageOverlay: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        height: 200,
        justifyContent: 'center',
        alignItems: 'center',
    },
    imagePremiumOverlay: {
        position: 'absolute',
        top: 0,
        width: '100%',
        height: '100%',
    },
    backButton: {
        position: 'absolute',
        top: 48,
        left: theme.spacing.md,
        width: 38,
        height: 38,
        borderRadius: 12,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        ...theme.shadows.medium,
        borderWidth: 1,
        borderColor: theme.colors.white,
        zIndex: 10,
    },
    contentContainer: {
        padding: theme.spacing.xl,
        paddingTop: theme.spacing.lg,
        backgroundColor: theme.colors.white,
    },
    categoryBadge: {
        alignSelf: 'flex-start',
        backgroundColor: theme.colors.primary,
        paddingHorizontal: theme.spacing.md,
        paddingVertical: theme.spacing.xs,
        borderRadius: theme.borderRadius.md,
        marginBottom: theme.spacing.md,
        ...theme.shadows.small,
        borderWidth: 1,
        borderColor: theme.colors.darkPink,
    },
    categoryText: {
        color: theme.colors.white,
    },
    name: {
        fontSize: theme.fontSizes.xxl,
        fontWeight: 'bold',
        color: theme.colors.black,
        marginBottom: theme.spacing.md,
        textAlign: 'left',
        fontFamily: 'PlayfairDisplay-Bold',
        textShadowColor: 'rgba(0, 0, 0, 0.1)',
        textShadowOffset: { width: 0.5, height: 0.5 },
        textShadowRadius: 1,
    },
    price: {
        color: theme.colors.accent,
        fontWeight: 'bold',
        fontFamily: 'Poppins-Bold',
        marginBottom: theme.spacing.xs,
        textShadowColor: 'rgba(212, 175, 55, 0.3)',
        textShadowOffset: { width: 0.5, height: 0.5 },
        textShadowRadius: 2,
    },
    divider: {
        height: 2,
        backgroundColor: theme.colors.primary,
        marginVertical: theme.spacing.lg,
        borderRadius: 1,
    },
    sectionTitle: {
        textShadowColor: 'rgba(0, 0, 0, 0.1)',
        textShadowOffset: { width: 0.5, height: 0.5 },
        textShadowRadius: 1,
        fontSize: theme.fontSizes.xl,
        fontWeight: 'bold',
        marginBottom: theme.spacing.sm,
        marginTop: theme.spacing.md,
    },
    description: {
        color: theme.colors.gray,
        textAlign: 'left',
        marginBottom: theme.spacing.lg,
        lineHeight: 28,
        fontSize: theme.fontSizes.md,
        fontFamily: 'Playfair Display',
    },
    storageCare: {
        color: theme.colors.gray,
        textAlign: 'left',
        lineHeight: 28,
        fontSize: theme.fontSizes.md,
        fontFamily: 'Playfair Display',
    },
    detailsContainer: {
        marginTop: theme.spacing.md,
        marginBottom: theme.spacing.lg,
        backgroundColor: theme.colors.secondary,
        borderRadius: theme.borderRadius.lg,
        padding: theme.spacing.md,
        ...theme.shadows.small,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: theme.spacing.sm,
        paddingVertical: theme.spacing.xs,
    },
    footer: {
        padding: theme.spacing.xl,
        backgroundColor: theme.colors.white,
        borderTopWidth: 2,
        borderTopColor: theme.colors.primary,
        ...theme.shadows.large,
    },
    addButton: {
        width: '100%',
        minWidth: '100%',
        shadowColor: theme.colors.accent,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    loadingIndicator: {
        marginVertical: 20,
    },
    unavailableText: {
        color: theme.colors.gray,
        textAlign: 'center',
    }
});
