export const theme = {
  colors: {
    primary: '#F7C7D9',
    secondary: '#FFF5F8',
    accent: '#D4AF37',
    darkPink: '#E8A3B8',
    white: '#FFFFFF',
    black: '#2C2C2C',
    gray: '#8E8E8E',
    lightGray: '#F5F5F5',
    textDarkPink: '#B45C7D',
    quaternary: '#FFE4E8',
    warning: '#FF6B6B',
    darkgray: '#4A4A4A',
  },
  fonts: {
    heading: 'Playfair Display',
    body: 'Poppins',
  },
  fontSizes: {
    s: 10,
    xs: 12,
    sm: 14,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
    xxxl: 40,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 6,
    },
  },
};
